version: "3"

services:
  mindingconfort:
    working_dir: /root/comfortFrontgit
    build: ./docker
    volumes:
      - ./code:/root/comfortFront
    container_name: vue--comfortFront
    hostname: comfortFront
    ports:
      - 8090:3000
    command: npm run dev
    tty: true
# certbot:
#   image: certbot/certbot
#   volumes:
#     - ./certbot/conf/:/etc/letsencrypt/:rw
#     - ./certbot/www/:/var/www/certbot/:rw
#networks:
#  metrogas:
#    external: true
#  aiguasol:
#    external: true

#external_links:
#  - mariadb
#networks:
#  - aiguasol
