version: "2"

services:
  aiguasolweb:
    build: node:17.5.0
    volumes:
      - ./code_aiguasolWeb:/var/www/html/aiguasolWeb
      - ./phpSettings.conf:/usr/local/etc/php-fpm.conf
      - ./logs/php:/var/log
    container_name: aiguasolWeb
    external_links:
      - mariadb
    networks:
      - aiguasol
  appsolweb:
    build: ./php_5_6_WP/
    volumes:
      - ./code_appsolWeb:/var/www/html/appsolWeb
      - ./phpSettings.conf:/usr/local/etc/php-fpm.conf
      - ./logs/php:/var/log
    container_name: appsolWeb
    external_links:
      - mariadb
    networks:
      - aiguasol
  nginx:
    user: root
    image: nginx:latest
    ports:
      - 80:80
      - 82:443
      - 443:443
      - 8084:81
      - 8085:82
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./certbot/www:/var/www/certbot/:ro
    volumes_from:
      - aiguasolweb
      - appsolweb
      - container:php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: nginx
    links:
      - aiguasolweb
    external_links:
      - php:php
    networks:
      - metrogas
      - aiguasol
  certbot:
    image: certbot/certbot
    networks:
      - aiguasol
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
networks:
  metrogas:
    external: true
  aiguasol:
    external: true
